"""Add revoked fields to refresh token

Revision ID: 3d4e0f4a10b7
Revises: 1a0a8aacca5e
Create Date: 2026-07-14 02:13:34.004000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4e0f4a10b7'
down_revision: Union[str, Sequence[str], None] = '1a0a8aacca5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "refresh_tokens",
        sa.Column(
            "is_revoked",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "refresh_tokens",
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    # Remove the default for future inserts
    op.alter_column(
        "refresh_tokens",
        "is_revoked",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'revoked_at')
    op.drop_column('refresh_tokens', 'is_revoked')
    # ### end Alembic commands ###
